### ISSUE TITLE
how to make 'mount' work?

### ISSUE THREAD

**Issue by N8c0der** [phhusson/sas-creator#14]
hi there,
i'm new to AOSP. i got a sony-lena(10iii) device that i like, except for beeing bloated by google stuff that i don't need. after searching a custom rom that meets my needs i ended up with phh-treble-gsi. the roar-floss version is actual on service on my lena. "just some little modifications would be nice."
so i decided to try your treble-experimentation-build-scripts. - nice job you've done!
sadly i struggle because 'mount -o loop,rw s.img d'(sas-creator/run.sh) keeps failing.
i am on LinuxMint 21 and tried some workarounds to 'mount as user'.
i put up LM21 just for AOSP-stuff and i've successfully compiled vanilla AOSP11 as instructed by sony.

has anyone ideas how to modify my machine or script?

**Comment by phhusson** [comment]
Without actually showing what's the error message is, it is pretty hard.
But I would guess that you're not running the script as root.

**Comment by N8c0der** [comment]
"+ mount -o loop,rw s.img d
mount: d: failed to setup loop device for /home/$USER/PHH/Lineage/sas-creator/s.img"

thank you for your quick response. and for surprising me: do you run your build.sh script as root?
should i 'sudo' build.sh?
(build.sh clones sas-creator and calls run.sh/lite-adapter.sh)

i would prefer to setup the loopdevice properly for rootless mount. if that is my issue.

all ideas are appreciated!

**Comment by phhusson** [comment]
Sorry I don't know how to setup loopback devices root-lessly

**Comment by N8c0der** [comment]
mercy beaucoup!
i close this thread with solution: run as root!
